spring:
  cloud:
    config:
      server:
        git:
#          uri: https://gitee.com/zhudeming/spring-cloud-config.git
          uri: http://localhost:3000/TechLearning/spring-cloud-config.git
          username: andy
          password: 123456
          search-paths: SC-BOOK-CONFIG
    bus:
      trace:
        enabled: true

  ## 配置rabbitMQ 信息
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10   # spring admin
    health-check-url-path: /actuator/health  # spring admin
    prefer-ip-address: true

