#spring:
#  boot:
#    admin:
#      client:
#        url: http://localhost:8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    #    leaseRenewalIntervalInSeconds: 10   # spring admin
    #    health-check-url-path: /actuator/health  # spring admin
    prefer-ip-address: true
logging:
  level:
    com.codedocker.springcloud.BookFeignClient: debug
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 7000
  ReadTimeout: 7000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
