#spring:
#  boot:
#    admin:
#      client:
#        url: http://localhost:8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    #    leaseRenewalIntervalInSeconds: 10   # spring admin
    #    health-check-url-path: /actuator/health  # spring admin
    prefer-ip-address: true

sidecar:
  port: 3001
  home-page-uri: http://localhost:${sidecar.port}/
  health-uri: http://localhost:${sidecar.port}/health
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
